name: GoblinsRegion
version: '1.0-SNAPSHOT'
main: Regula.goblinsRegion.GoblinsRegion
api-version: '1.20'
commands:
  filltownydb:
    description: "Заполняет базу данных городов и наций Towny."
    usage: "/filltownydb"
  regions:
    description: "Меню настройки регионов."
    usage: "/regions"
  changeregion:
    description: Открывает меню списка регионов.
    usage: /changeregion
    permission: RegionModer