name: GoblinsRegion
version: '1.0-SNAPSHOT'
main: Regula.goblinsRegion.GoblinsRegion
api-version: '1.20'
commands:
  filltownydb:
    description: "Заполняет базу данных городов и наций Towny."
    usage: "/filltownydb"
  regions:
    description: "Меню настройки регионов."
    usage: "/regions"
  changeregion:
    description: "Открывает меню списка регионов."
    usage: /changeregion
    permission: RegionModer
  regionpropertiesadmin:
    description: "Открывает свойства указанного города"
    usage: "/regionpropertiesadmin <город>"
  regionchangeproperties:
    description: "Изменить свойства региона"
    usage: /regionchangeproperties <property> <townName>
    permission: RegionModer
    permission-message: "У вас нет прав для выполнения этой команды."
  regionchangeresources:
    description: "Открывает меню ресурсов для города"
    usage: "/regionchangeresources <город>"